### ISSUE TITLE
Is the project completed?

### ISSUE THREAD

**Issue by chengyu0910** [Lovely-XPP/Birds-Keypoints-Detection#1]
Hi, thanks for your sharing! I want to know whether the project have been completed?

**Comment by Lovely-XPP** [comment]
Actually yes, maybe its result is not well. I think the amount of the dataset is small. However I have not enough time to label more pics now. I will check the codes and complete the ReadMe recently. Thanks for your asking.

**Comment by Lovely-XPP** [comment]
I updated the repo just now and if you have any problems, welcome to ask. By the way, I will upload the whole project  (including the dataset files) in the release.

**Comment by chengyu0910** [comment]
> I updated the repo just now and if you have any problems, welcome to ask. By the way, I will upload the whole project (including the dataset files) in the release.

Thanks for your reply! Will the trained-model parameters be shared with the dataset?

**Comment by Lovely-XPP** [comment]
Yes, I will also add to the release, I am uploading.

**Comment by Lovely-XPP** [comment]
All things have been done, you can check it in release page.
