### ISSUE TITLE
model file

### ISSUE THREAD

**Issue by flynnamy** [Lovely-XPP/Birds-Keypoints-Detection#2]
Hi, could you please share the model_final.pth file of the demo with baidu cloud disk? Thanks! @Lovely-XPP

**Comment by Lovely-XPP** [comment]
Okey, wait a minute, I am uploading.

**Comment by Lovely-XPP** [comment]
Done, Here is link: https://pan.baidu.com/s/1O8iTm0sd_v_9XL2IjD3Khg?pwd=qnp8 
and the password: `qnp8`

The model_final.pth is included in the output.zip. You can extract them to the root dir of the repo, so you can use the origin code without any changes.
